---
galaxy_info:
  role_name: powerdns
  author: Dmytro Rybak
  description: PowerDNS authoritative + recursor on Debian
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - trixie
dependencies: []
