apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: vm
  namespace: monitoring
spec:
  retentionPeriod: 30d
  port: "8428"
  storage:
    storageClassName: openebs-hostpath
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 20Gi
  resources:
    requests:
      cpu: 100m
      memory: 512Mi
    limits:
      memory: 1Gi
