apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflare-api-token
spec:
  vaultAuthRef: vault/default
  mount: secret
  path: core/cloudflare-api-token
  type: kv-v2
  refreshAfter: 1h
  destination:
    name: cloudflare-api-token
    create: true
