apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: cloudflared-credentials
spec:
  vaultAuthRef: vault/default
  mount: secret
  path: core/cloudflared-credentials
  type: kv-v2
  refreshAfter: 1h
  destination:
    name: cloudflared-credentials
    create: true
    transformation:
      excludeRaw: true
