apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victoriametrics
  namespace: monitoring
spec:
  instanceSelector:
    matchLabels:
      dashboards: grafana
  datasource:
    name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://vmsingle-vm.monitoring.svc:8428
    isDefault: true
    jsonData:
      timeInterval: 30s
