apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.21.0
      chart: cert-manager
      helm:
        releaseName: cert-manager
        valuesObject:
          crds:
            enabled: true
    - repoURL: https://github.com/homelabzero/homelab-core
      targetRevision: HEAD
      path: kubernetes/cloudflare
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3
