apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnativepg
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://cloudnative-pg.io/charts
    targetRevision: 0.29.0
    chart: cloudnative-pg
    helm:
      releaseName: cloudnative-pg
      valuesObject:
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            memory: 512Mi
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3
