apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/dmytro-rybak/homelab
    targetRevision: HEAD
    path: kubernetes/gateway
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
  revisionHistoryLimit: 3
